# Generated by Django 5.0.1 on 2024-01-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photonasa',
            options={'ordering': ['title'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
